language: php

php:
  - 8.2
  - 8.3
  - 8.4

matrix:
  include:
    - php: 8.2
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml
