language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml
